### ISSUE TITLE
Error when you do /say in the bot.py

### ISSUE THREAD

**Issue by NawtJ0sh** [notnola/pinychat#18]
If anyone can fix that.

**Comment by TechWhizZ199** [comment]
What is the error exactly and have you tried the beta version?

**Comment by ghost** [comment]
Pinychat is deprecated and not being maintained. Please move to https://github.com/nortxort/pinylib     nortxort is doing a wonderful of keeping the repo maintained and up to date. He has also extended Pinychat by quite a bit. Refer anyone you know using Pinychat to move to Pinylib at this point.

**Comment by NawtJ0sh** [comment]
Okay I will,  thanks.

**Comment by swiftSwathSee** [comment]
@Autotonic Not true. I've just been using a private version for the last 4 months that I finally got around to begin partially-releasing this week.

**Comment by GoelBiju** [comment]
Repository moved to legacy status, please use the sample_client.py in pinylib.
