### ISSUE TITLE
PinyChat bot is not able to connect anymore..

### ISSUE THREAD

**Issue by TechWhizZ199** [notnola/pinychat#3]
The bot will fetch the cauth from room server and then cannot proceed to connect.

**Comment by notnola** [comment]
https://github.com/notnola/pinychat/commit/8d9cf7c7b592bb5c85f428980d7a703122714564/

fixed

**Comment by TechWhizZ199** [comment]
Thanks.

Tech

From: notreallynola
Sent: ‎Thursday‎, ‎23‎ ‎July‎ ‎2015 ‎04‎:‎47
To: notnola/pinychat
Cc: TechWhizZ199

https://github.com/notnola/pinychat/commit/8d9cf7c7b592bb5c85f428980d7a703122714564/

fixed
