### ISSUE TITLE
Word mentions

### ISSUE THREAD

**Issue by swiftSwathSee** [notnola/pinychat#30]
Get notified whenever certain phrases are mentioned. Like your nick.

Pretty much just like IRC.

**Comment by swiftSwathSee** [comment]
Added in c073c83.

**Comment by ghost** [comment]
What sort of alert of this? Flashing terminal or?

**Comment by swiftSwathSee** [comment]
@Autotonic Just a highlight for now, but eventually it'll be window titlebar like the PMs have, which on some OSes does cause the terminal icon to flash. I'll also probably add a centralized alert management system that shows all alerts (PMs, mentions, etc.), much like the PM list mode right now.
