### ISSUE TITLE
PMs have empty line after them

### ISSUE THREAD

**Issue by swiftSwathSee** [notnola/pinychat#34]
An empty line is printed after each for some reason.

**Comment by ghost** [comment]
I cannot this reproduce under Windows Server 2012 R2 (cmd and cmder), Windows 7 (cmd), Debian (console), ArchLinux (lxterminal), or SliTaz Linux (xterm). It is also not apparent in the logs of any. Providing a few more details may help.

**Comment by swiftSwathSee** [comment]
Only seeing it in Cygwin.

**Comment by TechWhizZ199** [comment]
I, similarly, have yet to encounter this issue.
