### ISSUE TITLE
Can't PM nicks that contain capital letters

### ISSUE THREAD

**Issue by swiftSwathSee** [notnola/pinychat#35]
I think after the latest Tinychat client update 2 days ago, PMs might not be working 100% of the time. This is the TC update that added capital letters to nicks. Seems to happen randomly, haven't really tested it yet to fully reproduce this issue.

**Comment by TechWhizZ199** [comment]
There should not have been a change. They have not changed anything related to private messages as far as I know.

**Comment by swiftSwathSee** [comment]
I did more testing and have confirmed this bug. The issue is that most of the time, you can't PM (either reply or initiate) users with capital letters in their nicks. To clarify, by "can't PM" I mean that one of the following things happens:
- Outcome 1: The module shows it as being sent, but the user never actually receives it. 
- Outcome 2: The module never sends it and says that the user doesn't exist.

I've found that this bug doesn't seem to happen in older versions of the module ([like this one from August 2015](/notnola/pinychat/tree/0bafd3c93023d737917a598ccbbf2b657000793d)). In that old version, however, there is a bug where you can't PM users that have changed their nicks after you've enter the room. This suggests that somewhere along the line, nick changes aren't being fully processed by the module. Since the core PM functionality of the module hasn't changed since that version, I suspect that bug is related to the one we're discussing now. Furthering this suspicion is the fact that I've actually encountered this bug many times before Tinychat's recent allow-uppercase update, but I just never reported it.

**Comment by swiftSwathSee** [comment]
> This suggests that somewhere along the line, nick changes aren't being fully processed by the module.

Note that my fix probably didn't address this, so it might come up later again in another issue.
