### ISSUE TITLE
More obvious indicator that you're already banned

### ISSUE THREAD

**Issue by swiftSwathSee** [notnola/pinychat#36]
Currently there are only non-obvious indicators that you're already banned from a room. The indicators are either of these: your nick never changes from guest, you never see the topic, if notifications are off there's only one empty line instead of two after the "Connected to", (edit:) or if the module crashes after your first message.

There needs to be a more obvious indicator.

**Comment by notnola** [comment]
As I thought was the case, when connecting to a room that you are banned from, you will receive a packet that contains "banned" in its body... 
To fix simply add a statement to check for "banned" in listen(). - This may not be the case, I have not looked at the code in quite a while. School is eating my life.

![wireshark](https://cloud.githubusercontent.com/assets/9591067/13102500/0be8a0a0-d51d-11e5-851d-641d92227dbf.png)

I hope this helps!
-nola

**Comment by TechWhizZ199** [comment]
I'll quickly put this in.

EDIT: Just submitted a pull request for this issue. This should fix this problem; I am sure the solution can be developed on further but it is only a two line fix for now.

**Comment by swiftSwathSee** [comment]
I'm not seeing this `banned` message at connection (although I only checked the `cmd` variable right after [the `pars = msg['command']` line](https://github.com/notnola/pinychat/blob/master/tinychat.py#L356)). Also, I suspect it's for _any_ time you're disconnected, rather than only when you're banned, because it's also sent when Tinychat disconnects you for breaking their "only one session per account at any given time" rule.
