### ISSUE TITLE
No way to close your own cam

### ISSUE THREAD

**Issue by swiftSwathSee** [notnola/pinychat#39]
`/close` is only used by mods.

**Comment by notnola** [comment]
For the life of me I can't remember how the flash client does this. I don't have a development environment set up currently, but when I get home in a few hours I can provide a pcap and screenshot of the packet that turns your own stream off.

**Comment by TechWhizZ199** [comment]
A 'closeStream' RTMP (AMF) message is the easiest way you can close a bot generated camera stream.

EDIT: Submitted a new pull request with a 'CloseStream' to enable this feature.

**Comment by swiftSwathSee** [comment]
Fixed in 6abba8e.
