### ISSUE TITLE
Notify you if a user you were PMing has left, to avoid the chance of impersonation

### ISSUE THREAD

**Issue by swiftSwathSee** [notnola/pinychat#41]
PMed users are currently only tracked by nick, rather than of by some sort of session-unique ID. So if  you're PMing a nick and that nick leaves, and then someone else joins with that same nick, you could accidentally assume that this new person under the same nick is the original person. This assumption can be mitigated by just letting you know that the nick you were PMing has left, just like the Flash client already does.

**Comment by TechWhizZ199** [comment]
Good idea. Not too hard to implement.
