### ISSUE TITLE
Offical Developer Communications Channel

### ISSUE THREAD

**Issue by notnola** [notnola/pinychat#43]
During my few minutes of spare time over the next few days, I will be creating an offical channel for direct and instant communications between developers and community members.

I was thinking about launching a channel on Freenodes' IRC server and providing a web client on Pinychat's .io domain for thouse without an IRC client installed on their machine, or possibly setting up an offical Ti ychat room and embedding it on the .io domain.

Ideas are more than welcome and well receive proper consideration, however if there is no recommendations in the next few days, I'll move forward with one of the plans stated above.

-Regards,
---Nola

**Comment by TechWhizZ199** [comment]
I thought there already was one(?).

**Comment by ghost** [comment]
TechWhizZ199, nortxort, A (along with a few of her coder friends), and myself have been using /ccpd as the test bed for bot testing and related subjects. You are more than welcome to join and embed it in the .io domain. I recommend embedding with A's colored client, I can supply the needed javascript and html.

**Comment by notnola** [comment]
I think embedding Tinychat's client into [Pinychat's Github.io page](https://notnola.github.io/pinychat/) will be the best option, and that is precisely what I am going to do. Although I am not entirely sure if it is going to work due to limitations Github imposes on the types of content allowed. If it doesn't work, I will just host it myself.

@Autotonic, feel free to shoot me the Java and HTML via Skype when you can, so I can get this party started. 
--Regards,
----nola
