### ISSUE TITLE
Can't connect any more

### ISSUE THREAD

**Issue by swiftSwathSee** [notnola/pinychat#47]
Haven't been able to connect for the past few weeks. Or to be specific, Tinychat's servers don't seem to be sending and receiving messages to and from the module.

**Comment by TechWhizZ199** [comment]
This is an update issue which they have performed on their servers, the original RTMP module cannot cope with this and must be modified. Swift just to let you know we have made a group at [/asiansoul](https://tinychat.com/asiansoul) or [oddballz](https://github.com/oddballz/). Nola and Nort have moved over along with several others who are helping the repository. We have come up with a fix for this. Just pop on over later or see if Aida is online and talk to him and he can add you to the group.

**Comment by TechWhizZ199** [comment]
Just to note, the development version of the bot is kept on a private workspace. The current repository doesn't features any of the updates, so that's why I was asking if you would like to ask Aida to add you to the group.

**Comment by spyc0** [comment]
gimmie dat pinychat dev group pl0x - spyc0 (tc com/l3l)

**Comment by TechWhizZ199** [comment]
It's not actually pinychat, we are using the [pinylib](https://github.com/Nortxort/pinylib/) library and the bot based on that by the group, [pinybot](https://github.com/oddballz/pinybot/).

**Comment by swiftSwathSee** [comment]
**Back on topic:**

Good news! I just discovered that for some reason [my last commit](https://github.com/notnola/pinychat/tree/d32b9fbf05431e871d14bc888b81991d2935fb52) still fully works with all unregistered rooms, but only some registered rooms. For the registered rooms, I don't know what the criteria is, but my testing hints that it might be rooms that haven't been in the directory for 1-3 days. 

My tests were very simple and involved zero packet sniffing, so I encourage anyone that already has packet sniffing set up and is already intimately familiar with the RTMP side of things to start investigating.
