### ISSUE TITLE
Not really sure how to suggest a file..

### ISSUE THREAD

**Issue by nortxort** [notnola/pinychat#5]
https://github.com/nortxort/Project-1/blob/master/tinyMedia.py

**Comment by notnola** [comment]
:) I'll work this stuff in when I have the time. Thanks for the suggestions. 
Also, the proper way to make modification to the code here is to fork it, and then submit a pull request to the original git.

**Comment by TechWhizZ199** [comment]
Close this unless it is still pertinent.
