### ISSUE TITLE
No unicode support

### ISSUE THREAD

**Issue by swiftSwathSee** [notnola/pinychat#9]
All non-ASCII characters end up as gibberish.

**Comment by notnola** [comment]
I can't foresee this making or breaking anything to the module, or the bot. While this issue is now marked as "wontfix".

I am working on a Python3 version of this code. Stay tuned for a py3 branch soon.

**Comment by swiftSwathSee** [comment]
Any updates?

**Comment by GoelBiju** [comment]
@notnola , @swiftSwathSee  this has been implemented in pinylib.
